Bug 828030: only show dbcron output on failure; r=Callek

diff --git a/modules/mozpool/templates/dbcron.sh.erb b/modules/mozpool/templates/dbcron.sh.erb
--- a/modules/mozpool/templates/dbcron.sh.erb
+++ b/modules/mozpool/templates/dbcron.sh.erb
@@ -1,2 +1,7 @@
-# This just runs the 'dbcron' stored procedure
-mysql -h <%= scope.lookupvar('::mozpool::settings::db_hostname') %> --user=<%= scope.lookupvar('::mozpool::settings::db_username') %> --password='<%= scope.lookupvar('::mozpool::settings::db_password') %>' <%= scope.lookupvar('::mozpool::settings::db_database') %> -e 'call dbcron();'
+# This just runs the 'dbcron' stored procedure. The query sends diagnostic
+# output even on success, so this script only feeds that to cron on failure.
+mysql -h <%= scope.lookupvar('::mozpool::settings::db_hostname') %> --user=<%= scope.lookupvar('::mozpool::settings::db_username') %> --password='<%= scope.lookupvar('::mozpool::settings::db_password') %>' <%= scope.lookupvar('::mozpool::settings::db_database') %> -e 'call dbcron();' > /tmp/dbcron.output
+if [ $? != 0 ]; then
+        cat /tmp/dbcron.output
+        exit 1
+fi
